set (CMAKE_SYSTEM_NAME Linux)
set (CMAKE_SYSTEM_PROCESSOR aarch64)

set(CC gcc)
set(CXX g++)

if (WIN32)
    set(BIN_EXTENSION ".exe")
endif(WIN32)
    

set(CMAKE_C_COMPILER "aarch64-linux-gnu-${CC}${BIN_EXTENSION}")
set(CMAKE_CXX_COMPILER "aarch64-linux-gnu-${CXX}${BIN_EXTENSION}")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
